其实Numpy之类的单讲特别没意思，但不稍微说下后面说实际应用又不行，所以大家就练练手吧

代码裤子： <a href="https://github.com/lotapp/BaseCode" target="_blank">https://github.com/lotapp/BaseCode</a>

在线编程： <a href="https://mybinder.org/v2/gh/lotapp/BaseCode/master" target="_blank">https://mybinder.org/v2/gh/lotapp/BaseCode/master</a>

在线地址：<a href="http://github.lesschina.com/python/ai/numpy" target="_blank">https://www.cnblogs.com/dotnetcrazy/p/9309555.html</a>

## 1.数组定义、常见属性

引入一下`Numpy`模块，`Numpy`的数组使用可以查看一下帮助文档，`Numpy`的`array`数组类型必须是一致的（后面会讲）

In [1]:
# 导入Numpy模块
import numpy as np

In [2]:
help(np.array) #或者用 np.array? 查看

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

### 1.1.通过List创建数组

`np.array(list)`

**注意**：

`print(np.array([1,2,3,4,5]))`和`np.array([1,2,3,4,5])`

**在交互摸索下显示是稍微有点区别的**，千万别以为是不一样的东西



In [3]:
# 构造一个list1
list1 = list(range(10))
print(list1)

# 通过List创建一个一维数组
array1 = np.array(list1)

print(array1)
type(array1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [4]:
# 你直接写也一样
test_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(test_array)
type(test_array)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [5]:
# 创建一个嵌套列表
list2 = [list1,list1]
print(list2)

# 通过嵌套列表创建二维数组
array2 = np.array(list2)
print(array2)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [6]:
# 创建3维数组
array3 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]]
])

print(array3)
type(array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


numpy.ndarray

In [7]:
################### 扩展部分 ########################

# 其实你通过元组创建也一样，只是官方演示文档里面用的是list

# 逆天推荐使用列表（和官方文档一致嘛）

In [8]:
# 一维数组
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [9]:
# 都是一个数组，你print和直接输入名字是稍微有点区别的
# 千万别以为是不一样东西

print(np.array((1,2,3,4,5)))

[1 2 3 4 5]


In [10]:
# 二维数组
np.array(((1,2,3),(4,5,6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 二维数组，这种方式也一样
np.array(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

### 1.2.常用属性

`ndim` 查看数组维度

`shape` 查看数组形状

`size` 查看数组含有多少元素（行*列）

`dtype` 查看元素的数据类型

In [12]:
help(array2)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [13]:
# 查看维度
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


In [14]:
# 数组的形状，Tuple类型
print(array1.shape)
print(array2.shape) # 2行10列
print(array3.shape)

(10,)
(2, 10)
(2, 3, 3)


In [15]:
# 查看总共多少元素（行*列）
array2.size

20

In [16]:
# 查看元素的数据类型
array2.dtype

dtype('int64')

In [17]:
################### 扩展部分 ########################

In [18]:
# Array元素类型都一致，如果不一致会以最大兼容来初始化

np.array([[1,2,3],[4,5,6.0]]) # 都变成Float类型了

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
# 指定类型
np.array([[1,2,3],[4,5,6]],dtype=float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
# 行元素的个数不一致的测试

test_list = [[1],[1,2]]
print(test_list)

test_array = np.array(test_list)

print(test_array)

print(test_array.dtype) # 全部变成了object

[[1], [1, 2]]
[list([1]) list([1, 2])]
object


### 1.3.通过arange和reshape创建数组

`range()`返回的是`range`对象，而 **`np.arange()`返回的是`numpy.ndarray() `**

两者都可以进行迭代，而`np.nrange`还是一个序列，可被当做向量使用

`range()`不支持步长为小数, **`np.arange()`支持步长为小数**

如果这些基础类型还不是很清楚，可以看我之前写的文章：<a href="https://www.cnblogs.com/dunitian/p/4822808.html#ai" target="_blank">https://www.cnblogs.com/dotnetcrazy/p/9155310.html</a>

---

**多维数组创建**：（reshape的 **行x列 != 元素个数** 就会报错）

创建3行5列的数组：`np.arange(15).reshape((3,5))`

告诉它多少列，自动求行：`np.arange(20).reshape((-1,5))`

告诉它多少行，自动求列：`np.arange(20).reshape((4,-1))`

In [21]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [22]:
list(range(5))

[0, 1, 2, 3, 4]

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
type(range(1,10))

range

In [25]:
# 用法和range差不多
array1 = np.arange(1,10) # [1,10)

print(array1)

type(array1)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [26]:
# 可以直接迭代
for i in array1:
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 

In [27]:
# Python里面的range不支持步长为小数
range(1,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [28]:
# 支持步长为小数
np.arange(1,10,0.5) # step为0.5

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [29]:
################### 开始变化 ########################

In [30]:
help(array1.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.



In [31]:
# 创建2维数组，参数传元组比较合适（官方案例也是元组）
np.arange(1,10,0.5).reshape((2,9))

array([[1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [32]:
# 3行5列
np.arange(15).reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
# 告诉它多少列，自动求行
np.arange(20).reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
# 告诉它多少行，自动求列
np.arange(20).reshape((4,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
# reshape的 **行x列 != 元素个数** 就会报错
np.arange(20).reshape(3,7)

ValueError: cannot reshape array of size 20 into shape (3,7)

### 1.4.创建随机数组

`np.random.randint` 生成给定范围内均匀分布的整数

`np.random.rand` 生成`[0,1)`之间均匀分布的随机数

`np.random.ranf` 生成均匀分布的浮点数字`[0.0, 1.0)`

`np.random.randn` 生成符合正态分布的随机数 

`np.random.normal` 从正态分布中返回符合你输入的均值与方差以及shape的值

扩展：`np.random.seed` 设置随机种子，一般不太用，特殊场景需要

In [36]:
# 生成一个给定范围内均匀分布的整数[0,10)
np.random.randint(10)

7

In [37]:
# 生成20个在[0,10)的整数
np.random.randint(10,size=20)

array([5, 6, 5, 2, 1, 6, 0, 1, 9, 3, 8, 9, 1, 0, 0, 5, 7, 2, 2, 7])

In [38]:
# 生成2*4的数组，取值范围在[0,5)
np.random.randint(5, size=(2, 4))

array([[1, 1, 0, 4],
       [4, 1, 4, 1]])

In [39]:
# 更多可以查看
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [40]:
# 均匀分布的随机数[0,1)
np.random.rand(10)

array([0.93052782, 0.52355788, 0.60162643, 0.57750512, 0.32934868,
       0.04529727, 0.1089536 , 0.98409213, 0.72327059, 0.93003607])

In [41]:
# 更多可以查看
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

In [42]:
# 均匀分布的浮点数字[0.0, 1.0)
np.random.ranf(10)

array([0.02181866, 0.87750098, 0.19618116, 0.5076408 , 0.86583221,
       0.56368598, 0.69047121, 0.97234975, 0.13002229, 0.38533132])

In [43]:
# 更多可以查看
help(np.random.ranf)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [44]:
# 创建10个符合正态分布的随机数
np.random.randn(10)

array([-0.25448705, -1.33181234, -0.51123031, -2.12012698,  0.52889404,
        0.76552993,  0.86535772,  0.05172692,  0.42584787,  0.56117651])

In [45]:
# 更多可以查看
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

In [46]:
# 符合均值为0，方差为1的正态分布的浮点数
np.random.normal()

0.5187472471641197

In [47]:
# 符合均值为10，方差为100的正态分布的浮点数
np.random.normal(10,100)

-87.6264354067521

In [48]:
# 符合均值为10，方差为100，3*2的正态分布矩阵
np.random.normal(10,100,(3,2))

array([[ 2.03119172e+02, -9.21914693e+01],
       [-1.29009041e+02, -6.62820766e-02],
       [-8.53437355e+01,  7.79160227e+01]])

In [49]:
# 更多可以查看
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

### 1.5.linspace创建等差数组

`np.linspace` 生成等差数列的数组

和arange不一样的是end值可以取到

In [50]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [51]:
# 创建一个从0~10，差值为1的等差数组
# 0~10总共11个数（和arange不一样的是end值可以取到）
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [52]:
# 0~20(总共22个数)差值为2的等差数组
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [53]:
# 也可以让end_index取不到
np.linspace(0,20,10,endpoint=False)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

## 2.数组常用方法

### 2.1.数组元素的获取

基础用法之前讲过，可以回顾一下：<a href="https://www.cnblogs.com/dotnetcrazy/p/9114691.html#2.1.Python" target="_blank">https://www.cnblogs.com/dotnetcrazy/p/9114691.html#2.1.Python</a>

简写：**`array_name[行,列]`** （行列都是从0开始）

其他写法：`array_name[行][列]`（**Numpy不建议这么写，多维数组用切片的时候语义容易偏差**，eg:`xx[:2][:2]`)

In [54]:
# 先用熟悉的一维数组
array1 = np.arange(10)

print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
# 取第一个元素
array1[0]

0

In [56]:
# 取最后一个元素
array1[-1]

9

In [57]:
# 取第二个元素
array1[1]

1

In [58]:
# 取倒数第二个元素
array1[-2]

8

In [59]:
################### 二维数组 ########################

In [60]:
test_array = np.array([[1,2,3],[4,5,6]])

print(test_array)

[[1 2 3]
 [4 5 6]]


In [61]:
# 获取元素4（行列都是从0开始）
test_array[1][0] # Numpy不建议这么写

4

In [62]:
# 获取元素4 简写
test_array[1,0]

4

In [63]:
# 获取第一行最后一个
test_array[0,-1]

3

In [64]:
# 获取最后一行倒数第二个元素
test_array[-1,-2]

5

### 2.2.多维数组的切片用法

**`array_name[行切片,列切片]`** eg：`test_array[1:3,1:3]`==> 取索引为1,2的行；取索引为1,2的列

基础用法之前讲过，可以回顾一下：<a href="https://www.cnblogs.com/dotnetcrazy/p/9155310.html#1.7.列表切片" target="_blank">https://www.cnblogs.com/dotnetcrazy/p/9155310.html#1.7.列表切片</a>

In [65]:
# 先用熟悉的一维数组
array1 = np.arange(100)

print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [66]:
# 全部取出来
array1[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [67]:
# 从索引为1～最后
array1[1::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [68]:
################### 切片开始 ########################

In [69]:
# 从第二个元素取到最后,step为10
array1[1::10]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [70]:
# [1,5) 从下标1取到下标4,下标为5的取不到
array1[1:5]

array([1, 2, 3, 4])

In [71]:
# 取下标为1～倒数第二个元素（end_index取不到）
array1[1:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [72]:
# 取前10个
array1[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# 取最后10个，可以理解为从索引-5的元素到最后
array1[-10:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [74]:
# 前11~20（eg：第二页）
array1[10:20]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [75]:
# 取80~90（eg:倒数第二页）
array1[-20:-10]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [76]:
# 前20个数，每两个取一个（eg:隔行换样式）
array1[:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
# 所有数每10个取一个（eg:test的时候十里挑一）
array1[::10]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [78]:
################### 二维数组 ########################

In [79]:
# 生成一个多维数组
test_array = np.arange(15).reshape(3,5)

print(test_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [80]:
# [行切片，列切片]
# 行：取第2行到最后，列：取第3列到最后
test_array[1:,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [81]:
# 所有行，最后一列
test_array[:,-1:]

array([[ 4],
       [ 9],
       [14]])

In [82]:
# 所有行，索引[0,2)列
test_array[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [83]:
# 索引1的行，索引1的列
test_array[1:2,1:2]

array([[6]])

In [84]:
# 上面的等同于test_array[1][1]
print(test_array[1,1])

6


In [85]:
# 取索引为1,2的行；取索引为1,2的列
test_array[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

### 2.3.unique、max、min、sum

`np.unique` 找出其中不重复的元素

`np.max` 找出其中最大的值

`np.min` 找出其中最小值

`np.sum` 求和系列

In [86]:
a = np.random.randint(5,size=(4,5))

print(a)

[[1 4 3 4 2]
 [1 0 1 1 3]
 [2 0 4 4 0]
 [3 3 1 0 3]]


In [87]:
# 找出其中不重复的元素
np.unique(a)

array([0, 1, 2, 3, 4])

In [88]:
# 找出其中最大的值
np.max(a) # 或者：a.max()

4

In [89]:
# 找出第1行最大值
np.max(a[0]) # 或者：max(a[0])

4

In [90]:
# 找出第3列最大值
np.max(a[:,2]) # 或者：max(a[:,2])

4

In [91]:
print(a)

[[1 4 3 4 2]
 [1 0 1 1 3]
 [2 0 4 4 0]
 [3 3 1 0 3]]


In [92]:
# 找出其中最小值
np.min(a) # a.min()

0

In [93]:
# 找出第1行最小值
np.min(a[0]) # min(a[0])

1

In [94]:
# 找出第3列最小值
np.min(a[:,2]) # min(a[:,2])

1

In [95]:
print(a)

[[1 4 3 4 2]
 [1 0 1 1 3]
 [2 0 4 4 0]
 [3 3 1 0 3]]


In [96]:
np.sum(a)

40

In [97]:
# 注意：这个是每一列分别求和
sum(a) 

array([7, 7, 9, 9, 8])

In [98]:
# 每一行
np.sum(a,axis=1)

array([14,  6, 10, 10])

In [99]:
# 每一列
np.sum(a,axis=0)

array([7, 7, 9, 9, 8])

In [100]:
# 求第1行和
np.sum(a[0]) # sum(a[0])

14

In [101]:
# 求第3列和
np.sum(a[:,2]) # sum(a[:,2])

9

In [102]:
######### 扩展部分有两种写法的性能对比 #########

### 2.4.load导入、save导出

以前我们可能使用 pickle来实现，现在直接可以用自带的方法实现，eg：
```py
import pickle

f = open('x.dat','wb') # 写二进制文件
pickle.dump(array2,f) # 把对象array2写入f中
f.close()

f = open('x.dat','rb') # 读二进制文件
temp = pickle.load(f)
print(temp)
```
现在直接调用Numpy里面的方法即可
```py
np.save('file_name',obj)
np.load('file_name.npy')
```
多个文件：推荐用这种指定key的方式 默认以npz结尾:
```py
np.savez('file_name',obj1=obj1,obj2=obj2)
temp = np.load('file_name.npz')
temp[obj1]
temp.close()
```
也可以用扩展里面的方法

In [103]:
help(np.save)

Help on function save in module numpy.lib.npyio:

save(file, arr, allow_pickle=True, fix_imports=True)
    Save an array to a binary file in NumPy ``.npy`` format.
    
    Parameters
    ----------
    file : file, str, or pathlib.Path
        File or filename to which the data is saved.  If file is a file-object,
        then the filename is unchanged.  If file is a string or Path, a ``.npy``
        extension will be appended to the file name if it does not already
        have one.
    arr : array_like
        Array data to be saved.
    allow_pickle : bool, optional
        Allow saving object arrays using Python pickles. Reasons for disallowing
        pickles include security (loading pickled data can execute arbitrary
        code) and portability (pickled objects may not be loadable on different
        Python installations, for example if the stored objects require libraries
        that are not available, and not all pickled data is compatible between
        Python 2 and Py

In [104]:
!ls # 查看下当前目录

print(array2)

NumpyBase.ipynb  矩阵系列.ipynb
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [105]:
# 把array2对象保存成本地二进制文件（自动以.npy结尾）
np.save('bak',array2)

In [106]:
!ls

bak.npy  NumpyBase.ipynb  矩阵系列.ipynb


In [107]:
# 读取
np.load('bak.npy')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [108]:
################### 多个对象保存 ########################

In [109]:
help(np.savez)

Help on function savez in module numpy.lib.npyio:

savez(file, *args, **kwds)
    Save several arrays into a single file in uncompressed ``.npz`` format.
    
    If arguments are passed in with no keywords, the corresponding variable
    names, in the ``.npz`` file, are 'arr_0', 'arr_1', etc. If keyword
    arguments are given, the corresponding variable names, in the ``.npz``
    file will match the keyword names.
    
    Parameters
    ----------
    file : str or file
        Either the file name (string) or an open file (file-like object)
        where the data will be saved. If file is a string or a Path, the
        ``.npz`` extension will be appended to the file name if it is not
        already there.
    args : Arguments, optional
        Arrays to save to the file. Since it is not possible for Python to
        know the names of the arrays outside `savez`, the arrays will be saved
        with names "arr_0", "arr_1", and so on. These arguments can be any
        expression.

In [110]:
print(array1)
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [111]:
# 推荐用这种指定key的方式 默认以npz结尾
np.savez('good',array1=array1,array2=array2)

In [112]:
!ls

bak.npy  good.npz  NumpyBase.ipynb  矩阵系列.ipynb


In [113]:
temp = np.load('good.npz')

In [114]:
temp['array1']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [115]:
temp['array2']

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [116]:
################### 扩展系列 ########################

In [117]:
# 默认以npz结尾
np.savez('some',array1,array2)

In [118]:
!ls

bak.npy  good.npz  NumpyBase.ipynb  some.npz  矩阵系列.ipynb


In [119]:
temp = np.load('some.npz')

type(temp)

numpy.lib.npyio.NpzFile

In [120]:
# 知道有那些文件名，也就是对应的key了
keys = temp.files

print(keys)

['arr_0', 'arr_1']


In [121]:
# 通过这种方式获取
temp[keys[0]]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [122]:
temp[keys[1]]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

看个图就知道它多文件是啥意思了
![npy](https://images2018.cnblogs.com/blog/1127869/201807/1127869-20180714145334749-208486178.png)

### 2.5.合并系列（concatenate、hstack、vstack）

#### 2.5.1.`concatenate`

`np.concatenate(tuple,axis=0)` 默认是x轴拼接（上下、按照列顺序），`axis=1` => y轴拼接（左右、按照行顺序）

In [123]:
help(np.concatenate)

Help on built-in function concatenate in module numpy.core.multiarray:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
                  near-equal size.
  

In [124]:
A = np.random.randint(10,size=(2,3))

print(A)

[[3 6 6]
 [3 7 3]]


In [125]:
# 默认是上下（x轴）拼接，第一个参数是元组
np.concatenate((A,A))

array([[3, 6, 6],
       [3, 7, 3],
       [3, 6, 6],
       [3, 7, 3]])

In [126]:
# 左右（沿y轴）拼接
np.concatenate((A,A),axis=1)

array([[3, 6, 6, 3, 6, 6],
       [3, 7, 3, 3, 7, 3]])

#### 2.5.2.hstack and vstack

注意一点：concatenate只能处理一个维度的，如果维度不同可以使用容错性更强的`vstack`（垂直拼接）和`hstack`（水平拼接）

In [127]:
print(A)
print(new_test_array)

np.concatenate((A,new_test_array)) # 只能处理一个维度的

[[3 6 6]
 [3 7 3]]


NameError: name 'new_test_array' is not defined

In [128]:
help(np.hstack)

Help on function hstack in module numpy.core.shape_base:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
 

In [129]:
print(A)

np.hstack((A,A))

[[3 6 6]
 [3 7 3]]


array([[3, 6, 6, 3, 6, 6],
       [3, 7, 3, 3, 7, 3]])

In [130]:
np.vstack((A,A))

array([[3, 6, 6],
       [3, 7, 3],
       [3, 6, 6],
       [3, 7, 3]])

In [131]:
print(new_test_array)

np.hstack((A,new_test_array))

NameError: name 'new_test_array' is not defined

In [132]:
# 元素不够也是一样报错的
np.vstack((A,new_test_array))

NameError: name 'new_test_array' is not defined

In [133]:
help(np.vstack)

Help on function vstack in module numpy.core.shape_base:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new 

### 2.6.切割系列（split、hsplit、vsplit）

**按行切割** `np.split(test_array,[index])` 简化：`np.vsplit(test_array,[index])`

**按列切割** `np.split(test_array,[index],axis=1)` 简化：`np.hsplit(test_array,[index])`

In [134]:
A = np.random.randint(10,size=10) # np.arange(10)

print(A)

[8 7 0 7 8 6 3 0 1 2]


In [135]:
a,b = np.split(A,[2])

print(a)
print(b)

[8 7]
[0 7 8 6 3 0 1 2]


In [136]:
# 索引2、4分割
a,b,c = np.split(A,[2,4])

print(a)
print(b)
print(c)

[8 7]
[0 7]
[8 6 3 0 1 2]


In [137]:
################### 多维系列 ########################

In [138]:
test_array = np.random.randint(10,size=(4,5))

print(test_array)

[[2 6 3 2 3]
 [2 1 9 8 2]
 [1 7 9 6 3]
 [9 0 2 4 2]]


In [139]:
# 按行切割
a,b = np.split(test_array,[1])

print(a)
print(b)

[[2 6 3 2 3]]
[[2 1 9 8 2]
 [1 7 9 6 3]
 [9 0 2 4 2]]


In [140]:
# 简化写法
a,b = np.vsplit(test_array,[1])

print(a)
print(b)

[[2 6 3 2 3]]
[[2 1 9 8 2]
 [1 7 9 6 3]
 [9 0 2 4 2]]


In [141]:
# 按列切割
a,b = np.split(test_array,[1],axis=1)

print(a)
print(b)

[[2]
 [2]
 [1]
 [9]]
[[6 3 2 3]
 [1 9 8 2]
 [7 9 6 3]
 [0 2 4 2]]


In [142]:
# 简化写法
a,b = np.hsplit(test_array,[1])

print(a)
print(b)

[[2]
 [2]
 [1]
 [9]]
[[6 3 2 3]
 [1 9 8 2]
 [7 9 6 3]
 [0 2 4 2]]


In [143]:
help(np.split)

Help on function split in module numpy.lib.shape_base:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list of nd

### 2.7.扩展系列

#### 2.7.1.`np.copy`

我们先来看看为什么要用copy

In [144]:
test_list = list(range(10))
print(test_list)

# 在Python中切片是不改变原列表的
new_test_list = test_list[:5]
print(test_list)
print(new_test_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4]


In [145]:
# 修改切片出来的列表不影响原列表
new_test_list[0] = 22
print(test_list)
print(new_test_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[22, 1, 2, 3, 4]


In [146]:
# 再看看Numpy的数组
test_array = np.random.randint(10,size=(3,5))
print(test_array)

new_test_array = test_array[:2,:2]
print(new_test_array)
print(test_array)

[[4 5 1 0 1]
 [2 9 5 8 7]
 [0 7 0 6 2]]
[[4 5]
 [2 9]]
[[4 5 1 0 1]
 [2 9 5 8 7]
 [0 7 0 6 2]]


In [147]:
# Numpy只要效率，所以不是真的给你切出新数组
new_test_array[0,0]=22

print(new_test_array)
print(test_array)

[[22  5]
 [ 2  9]]
[[22  5  1  0  1]
 [ 2  9  5  8  7]
 [ 0  7  0  6  2]]


In [148]:
################### Copy登场 ########################

In [149]:
print(test_array)

temp = test_array.copy()
new_test_array = temp[:2,:2]

print(new_test_array)

[[22  5  1  0  1]
 [ 2  9  5  8  7]
 [ 0  7  0  6  2]]
[[22  5]
 [ 2  9]]


In [150]:
# 验证一下是不是真的copy，的确是真copy
new_test_array[0,0] = 6

print(new_test_array)
print(test_array)

[[6 5]
 [2 9]]
[[22  5  1  0  1]
 [ 2  9  5  8  7]
 [ 0  7  0  6  2]]


#### 2.7.2.效率测试（time、timeit）

In [1]:
import numpy as np

In [2]:
%%time
A = list(range(1000000))

CPU times: user 15.1 ms, sys: 11.9 ms, total: 27 ms
Wall time: 26.8 ms


In [3]:
%%time
A = np.arange(1000000)

CPU times: user 11.2 ms, sys: 7.34 ms, total: 18.6 ms
Wall time: 17.3 ms


In [4]:
# 之前讲sum、max、min提供两种写法，这次测试下
big_array = np.random.randint(10,size=(3,5))
%timeit np.sum(big_array[0])
%timeit sum(big_array[0])

5.52 µs ± 651 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.63 µs ± 52.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 2.7.3.统计相关（平均值、中位数、百分位、方差、标准差等）

后面有机会会说说数学里面的统计学，到时候还会再说的

In [5]:
A = np.arange(1,7).reshape(3,-1)

print(A)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
# 矩阵元素的乘积
np.prod(A)

720

In [7]:
# 平均值
np.mean(A)

3.5

In [8]:
# 中位数
# 把所有观察值高低排序后找出正中间的一个作为中位数
# 如果观察值有偶数个，通常取最中间的两个数值的平均数作为中位数
np.median(A)

3.5

In [9]:
# 百分数，在这些元素中百分之25的元素都是<=xxx的
np.percentile(A,q=25)

2.25

In [10]:
# 实际场景：样本分布情况
for i in [0,25,50,75,100]:
    print(np.percentile(A,q=i))

1.0
2.25
3.5
4.75
6.0


In [11]:
# 方差
np.var(A)

2.9166666666666665

In [12]:
# 标准差
np.std(A)

1.707825127659933

In [13]:
################### 变化开始 ########################

In [14]:
# 应用场景：正态分布验证
# eg:均值为0，标准差为1
test = np.random.normal(0,1, size=(100,50))

In [15]:
# 基本上等于0
np.mean(test)

0.004244947279570449

In [16]:
# 基本上为1
np.std(test)

0.9957424470098744

In [17]:
################### 灵活运用 ########################

In [18]:
A = np.arange(1,16).reshape(3,-1)

print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
# 有一个小于4就返回True
np.any(A < 4)

True

In [20]:
# 所有的都小于4才返回True
np.all(A < 4)

False

In [21]:
# 矩阵进行运算，都是针对所有元素的
A % 2 == 0

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [22]:
# 看有几个偶数
np.sum(A % 2 ==0)

7

In [23]:
# 每一行有几个
np.sum(A%2==0, axis=1)

array([2, 3, 2])

In [24]:
# 每一列
np.sum(A%2==0, axis=0)

array([1, 2, 1, 2, 1])

#### 2.7.4.索引相关扩展

主要是argxxx获得索引

`argmax` 获取最大值的索引

`argmin` 获取最小值的索引

`argsort`获取排序后的索引

`argpartition`以对应值为分割的索引

In [25]:
A = np.random.randint(10,size=(3,4))

print(A)

[[4 5 7 8]
 [6 7 6 3]
 [7 6 7 1]]


In [26]:
np.max(A)

8

In [27]:
# 获取最大值的索引
np.argmax(A)

3

In [28]:
np.min(A)

1

In [29]:
# 获取最小值的索引
np.argmin(A)

11

In [30]:
################### 分割线 ########################

In [31]:
# 先打乱一下
np.random.shuffle(A)

print(A)

[[4 5 7 8]
 [7 6 7 1]
 [6 7 6 3]]


In [32]:
# 对于矩阵，是每一行排序
np.sort(A)

array([[4, 5, 7, 8],
       [1, 6, 7, 7],
       [3, 6, 6, 7]])

In [33]:
# 注意一点：用np.sort(A)，A本身没变化，想要变化使用A.sort
A

array([[4, 5, 7, 8],
       [7, 6, 7, 1],
       [6, 7, 6, 3]])

In [34]:
# 返回原数组对应索引
np.argsort(A)

array([[0, 1, 2, 3],
       [3, 1, 0, 2],
       [3, 0, 2, 1]])

In [35]:
################### 分割线 ########################

In [36]:
# 先熟悉一下这个函数
A = np.random.randint(10,size=10)
print(A)

[5 7 6 3 8 0 3 7 5 8]


In [37]:
# 以4为分割，比4大的在前面，比4小的在后面（不排序）
np.partition(A,4)

array([0, 3, 3, 5, 5, 6, 7, 7, 8, 8])

In [38]:
# 返回对应索引
np.argpartition(A,4)

array([5, 3, 6, 8, 0, 2, 1, 7, 4, 9])

还有什么补充以后就添加在这