## 2.矩阵专栏

吐槽一下：矩阵本身不难，但是矩阵的写作太蛋疼了 `(⊙﹏⊙)汗` 还好有`Numpy`，不然真的崩溃了...

`LaTex`有没有一个集成了很多常用`公式`以及`推导`或者含`题库`的在线编辑器？

基础回顾：<a href="https://www.cnblogs.com/dotnetcrazy/p/9294292.html" target="_blank">https://www.cnblogs.com/dotnetcrazy/p/9294292.html</a>

### 2.1.矩阵的定义

<a href="https://baike.baidu.com/item/矩阵" target="_blank">https://baike.baidu.com/item/矩阵</a>：是一个按照长方阵列排列的复数或实数集合。

通俗讲就是：**把数排成m行n列后，然后用中括号把它们括住，这种形式的组合就是矩阵了**～ eg：

$\begin{bmatrix}
&a_{11}&a_{12}&a_{13}&...&a_{1n} \\
&a_{21}&a_{22}&a_{23}&...&a_{2n} \\
&a_{31}&a_{32}&a_{33}&...&a_{3n} \\
&\vdots&\vdots&\vdots&\ddots&\vdots\\
&a_{m1}&a_{m2}&a_{m3}&...&a_{mn} \\
\end{bmatrix}$

比如上面这个示例就是一个`m × n`的矩阵（m行n列的矩阵），如果`m=n`那么就叫做`n阶方阵`，eg:

$\begin{bmatrix}
1&2&3 \\
4&5&6 \\
7&8&9
\end{bmatrix}$

这个就是`3阶`方阵

---

如果回到中学，老师肯定都是通过**一次方程组**来引入矩阵（逆天的老师是这么讲的）：

$\begin{cases}x_1+x_2=-1\\2x_1-x_2=4\\3x_1+5x_2=-7\\\end{cases}$ ==>  $\begin{bmatrix}1&1\\2&-1\\3&5\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}=\begin{bmatrix}-1\\4\\-7\end{bmatrix}$

如果你方程组都忘记怎么解的话...好吧还是说下吧：“比如这题，可以先把x2移到右边，这样x1就等于一个表达式了（x1=-x2-1），然后带入第二个表达式就可以解出x1和x2了，一次的其实两个表达式就可以解出了，剩下的你可以把值带进去验证一下”

### 2.2.矩阵的运算（含幂运算）

#### 2.2.1.加、减

加减比较简单，就是**对应元素相加减** (只有`行列都相同的矩阵`才可以进行)

就不用麻烦的`LaTex`一行行打了，咱们用更方便的 **<a href="https://en.wikipedia.org/wiki/NumPy" target="_blank">NumPy</a>** 来演示一下矩阵加法（不懂代码的直接看结果，不影响阅读的）

扩展：**矩阵的加法运算满足交换律：A + B = B + A** (乘法不行)

In [1]:
import numpy as np

In [2]:
# 创建两个集合
A = np.arange(1,10).reshape(3,3)
B = np.arange(9).reshape(3,3)

print(A)
print("-"*5)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# 加法
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [4]:
# 和A+B相等
B + A

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [5]:
# 减法
A - B

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
################ 变化来了 ################

In [7]:
# 之前说过 ”只有行列都相同的矩阵才可以进行“ 来验证一下
# 创建一个2行3列的矩阵
C = np.arange(6).reshape(2,3) 
D = np.arange(6).reshape(3,2)

print(C)
print("-"*5)
print(D)

[[0 1 2]
 [3 4 5]]
-----
[[0 1]
 [2 3]
 [4 5]]


In [8]:
# 2行3列的矩阵 + 3行2列的矩阵
C + D # 不同形状的矩阵不能进行加运算

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [9]:
C - D # 不同形状的矩阵不能进行减运算

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

#### 2.2.2.数乘、数除

这个也比较简单，就是和**每个元素相乘**，eg:`2×A`，A原本的每一个元素都扩大了两倍

数除其实就是乘以倒数（1/x）

In [10]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# 比如2×A，A原本的每一个元素都扩大了两倍
2 * A

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [12]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
A / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

#### 2.2.3.矩阵乘法

矩阵乘法还是要用`LaTex`演示一下的，不然有些朋友可能还是觉得比较抽象：（大家有什么好用的LaTex在线编辑器可以推荐的）

拿上面那个方程组来演示一下：

$\begin{bmatrix}1&1\\2&-1\\3&5\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix} ==> \begin{cases}x_1+x_2\\2x_1-x_2\\3x_1+5x_2\end{cases}$

稍微变化一下就更形象了：

$\begin{bmatrix}1&1\\2&-1\\3&5\end{bmatrix}\begin{bmatrix}x_1&y_1\\x_2&y_2\end{bmatrix} ==> \begin{cases}x_1+x_2\\2x_1-x_2\\3x_1+5x_2\end{cases} \begin{cases}y_1+y_2\\2y_1-x_2\\3y_1+5y_2\end{cases}==>\begin{bmatrix}x_1+x_2&y_1+y_2\\2x_1-x_2&2y_1-y_2\\3x_1+5x_2&3y_1+5y_2\end{bmatrix}$

举个简单的例子：A×B

$\begin{bmatrix} 1&2 \\3&4 \end{bmatrix}\begin{bmatrix} 4&3 \\2&1 \end{bmatrix}=\begin{bmatrix} 1*4+2*2&1*3+2*1 \\3*4+4*2&3*3+4*1 \end{bmatrix}=\begin{bmatrix} 8&5 \\20&13 \end{bmatrix}$

以后记不得怎么乘就自己推一下，值得注意的是：

**两个矩阵的乘法仅当第一个矩阵A的列数(column)和另一个矩阵B的行数(row)相等才可以进行计算**

你这样想就记得了：$\begin{bmatrix} 1&2 \\3&4 \end{bmatrix}\begin{bmatrix} x_1 \end{bmatrix} 还原成方程组就是这样\begin{cases}1*x_1+2*?\\3*x_1+4*?\end{cases}\\这是什么鬼？至少得这样吧：\begin{bmatrix} 1&2 \\3&4 \end{bmatrix}\begin{bmatrix} x_1 \\x_2 \end{bmatrix}$


In [14]:
# 通过代码看一看
A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])

print(A)
print("-"*5)
print(B)

[[1 2]
 [3 4]]
-----
[[4 3]
 [2 1]]


In [15]:
# 注意一下，Numpy里面的乘法默认是数乘
# 如果是矩阵相乘可以使用dot()方法

A.dot(B) # 矩阵A×矩阵B

array([[ 8,  5],
       [20, 13]])

程序验证了我们上面的运算结果，还得注意一下：

`A×B`和`B×A`是不一样的，eg：B×A

$\begin{bmatrix} 4&3 \\2&1 \end{bmatrix}\begin{bmatrix} 1&2 \\3&4 \end{bmatrix}=\begin{bmatrix} 4*1+3*3&4*2+3*4 \\2*1+1*3&2*2+1*4 \end{bmatrix}=\begin{bmatrix} 13&20 \\5&8 \end{bmatrix}$

如果你乘着乘着就忘记到底怎么乘，就把右边的矩阵换成x1,x2，然后就会了

In [16]:
print(A)
print("-"*5)
print(B)

[[1 2]
 [3 4]]
-----
[[4 3]
 [2 1]]


In [17]:
B.dot(A) # 矩阵B×矩阵A

array([[13, 20],
       [ 5,  8]])

In [18]:
################ 变化来了 ################

In [19]:
# 来验证一下”两个矩阵的乘法仅当第一个矩阵A的列数(column)和另一个矩阵D的行数(row)相等才可以进行计算“
print(A)
print("-"*5)
print(D)

[[1 2]
 [3 4]]
-----
[[0 1]
 [2 3]
 [4 5]]


In [20]:
# A有2列 D有3行
A.dot(D) # 不能乘

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [21]:
# 你反过来就符合A的列数=D的行数了
D.dot(A)

array([[ 3,  4],
       [11, 16],
       [19, 28]])

#### 2.2.4.幂乘、幂运算

幂乘比较简单，就是**每个元素开平方**，不一定是方阵

必须是方阵才能进行<a href="https://baike.baidu.com/item/幂运算" target="_blank">幂运算</a>，比如`A²=A×A`（矩阵相乘前提：`第一个矩阵A的行=第二个矩阵A的列==>方阵`）

In [22]:
print(A)
print("-"*5)
print(C)

[[1 2]
 [3 4]]
-----
[[0 1 2]
 [3 4 5]]


In [23]:
# 幂乘(每个元素开平方) 
np.power(A,2)

array([[ 1,  4],
       [ 9, 16]])

In [24]:
# 幂乘(不一定是方阵) 
np.power(C,2)

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [25]:
################ 方阵幂运算 ################

In [26]:
# A*A*A
np.linalg.matrix_power(A,3)

array([[ 37,  54],
       [ 81, 118]])

In [27]:
# 不是方阵就over
np.linalg.matrix_power(C,3)

ValueError: input must be a square array

**来个小结 + 扩展**：

矩阵的加法运算满足交换律：`A + B = B + A`

矩阵的乘法满足结合律和对矩阵加法的分配律：

结合律：`(AB)C = A(BC)`

左分配律：`(A + B)C = AC + BC`

右分配律：`C(A + B) = CA + CB`

矩阵的乘法与数乘运算之间也满足类似结合律的规律；与转置之间则满足倒置的

分配律：`c(A + B) = cA + cB`

结合律：`c(AB) = (cA)B = A(cB)`

矩阵乘法**不满足交换律** 一般来说，矩阵A及B的乘积AB存在，但BA不一定存在，即使存在，大多数时候`AB ≠ BA`

### 2.3.特殊矩阵

#### 2.3.1.零矩阵

零矩阵就是所有的元素都是0

$
\begin{bmatrix}
0&0&0 \\
0&0&0 \\
0&0&0
\end{bmatrix}
$

同样的：**全1矩阵**就是所有元素都是1

$
\begin{bmatrix}
1&1&1 \\
1&1&1 \\
1&1&1
\end{bmatrix}
$

In [1]:
import numpy as np

In [2]:
# 一维
# 可以指定类型 np.zeros(5,dtype=int)
np.zeros(5) # 完整写法：np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [3]:
# 二维
np.zeros((2,5))# 建议用元组，官方文档都是元组

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
# 三维 ==> 可以这么理解，2个2*5（2行5列）的矩阵
np.zeros((2,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [5]:
################ 全1矩阵 ################

In [6]:
# `np.ones(tuple)` 用法和`np.zeros(tuple)`差不多
# 可以指定类型 np.ones(5,dtype=int)
# 一维
np.ones(5) # 完整写法 np.ones((5,))

array([1., 1., 1., 1., 1.])

In [7]:
# 二维，传一个shape元组
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# 三维 可以理解为两个二维数组
np.ones((2,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [9]:
################ 指定值矩阵 ################

In [10]:
# 创建指定值的矩阵：
np.full((3,5),222)

array([[222, 222, 222, 222, 222],
       [222, 222, 222, 222, 222],
       [222, 222, 222, 222, 222]])

In [11]:
# 创建指定值的矩阵，浮点类型
np.full((3,5),222.0)

array([[222., 222., 222., 222., 222.],
       [222., 222., 222., 222., 222.],
       [222., 222., 222., 222., 222.]])

#### 2.3.3.转置矩阵

**<a href="https://baike.baidu.com/item/转置矩阵" target="_blank">转置矩阵</a>** ：将矩阵的行列互换得到的新矩阵(行列式不变)

`m行×n列`的矩阵行和列交换后就变成了`n行×m列`的矩阵，eg：`3行×2列` ==> `2行×3列`

$\begin{bmatrix}1&2 \\3&4 \\5&6\end{bmatrix}^T ==> \begin{bmatrix}1&3&5 \\2&4&6\end{bmatrix}$

矩阵的转置满足分配律：

$(A + B)^T = A^T + B^T$

$(AB)^T = B^TA^T$

In [13]:
A = np.random.randint(10,size=(2,3))

print(A)

[[7 3 6]
 [5 3 1]]


In [14]:
# 转置矩阵（行列互换）
A.T

array([[7, 5],
       [3, 3],
       [6, 1]])

#### 2.3.3.对称矩阵

#### 2.3.4.上三角和下三角矩阵

#### 2.3.5.对角矩阵

#### 2.3.6.单位矩阵

#### 2.3.7.逆矩阵

原矩阵×逆矩阵=单位矩阵 and 逆矩阵×原矩阵=单位矩阵

非方阵可以求 **<a href="https://baike.baidu.com/item/伪逆矩阵" target="_blank">伪逆矩阵</a>** AXA=A,XAX=X

In [15]:
A

array([[7, 3, 6],
       [5, 3, 1]])

In [16]:
# 必须是方阵的验证
np.linalg.inv(A)

LinAlgError: Last 2 dimensions of the array must be square

In [23]:
# 有时候还是需要求逆矩阵
# 那就可以求它的伪逆矩阵
X = np.linalg.pinv(A)

print(X)

[[-0.00632911  0.15189873]
 [-0.05696203  0.16708861]
 [ 0.20253165 -0.26075949]]


In [24]:
# A*X*A=A
A.dot(X).dot(A)

array([[7., 3., 6.],
       [5., 3., 1.]])

In [25]:
# X*A*X=X
X.dot(A).dot(X)

array([[-0.00632911,  0.15189873],
       [-0.05696203,  0.16708861],
       [ 0.20253165, -0.26075949]])